web/router.ex
defmodule Runnel.Router do
  use Runnel.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth_browser do
    plug Runnel.RedirectOrSigninCookie
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Runnel do
    pipe_through :browser
    # pipe_through :auth_browser

    get "/", PageController, :index
    get "/show/:run_id", PageController, :show
  end

  scope "/auth", Runnel do
    pipe_through :browser

    get "/", AuthController, :index
    post "/create_session", AuthController, :create_session
  end
end

web/templates/page/index.html.eex
<%= for {_, activities} <- group_runs_by_month(@runs) do %>

  <div class="grid-container">
    <%= for activity <- activities do %>
      <div class="grid-cell">
        <div class="grid-cell-content run">
          <div class="overlay">
            <ul class="list-unstyled content run-data" data-waypoints=<%= activity.waypoints |> Poison.encode! %>>
              <li class="time"><%= Timex.format!(activity.start_time, "%d %B %Y", :strftime) %></li>
              <li><%= activity.duration %></li>
              <li class="important"><%= Float.round(activity.distance, 1) %>K RUN </li>
            </ul>

            <div class="map"></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

web/templates/page/run.html.eex
<div class="run">
  <div class="row">
    <div class="col-xs-12">
      <div class="wrapper">
        <div class="header">
          <h3><%= @data.start_time%></h3>
        </div>
        <div class="stats">
          <ul class="list-unstyled">
            <li><i class="fa fa-road fa-lg"></i><%= @data.distance %> Distance (Km)</li>
            <li><i class="fa fa-clock-o"></i><%= @data.duration %> Duration</li>
            <li><i class="fa fa-fire" ></i><%= @data.calories %> Calories</li>
          </ul>
        </div>
        <div class="map" data-waypoints=<%= @data.waypoints |> Poison.encode!  %>></div>
      </div>
      <%= link("list of runs", to: page_url(@conn, :index)) %>
    </div>
  </div>
</div>

web/templates/page/see_stuff.html.eex
<div class="grid-container">
  <%= for activity <- @data do %>
    <div class="col run-box run">
      <div class="wrapper">
        <div class="header">
          <h3> <%= link(activity.start_time, to: page_path(@conn, :show, activity.activity_id)) %> </h3>
        </div>

        <ul class="list-unstyled run-data stats" data-waypoints=<%= activity.waypoints |> Poison.encode! %>>
          <li><%= activity.duration %></li>
          <li><%= activity.distance %> km </li>
          <li><%= activity.calories %> calories </li>
        </ul>

        <div class="map2"></div>
      </div>
    </div>
  <% end %>
</div>

web/templates/page/show.html.eex
<div class="run">
  <div class="row">
    <div class="col-xs-12">
      <div class="wrapper">
        <div class="header">
          <h3><%= @data.start_time%></h3>
        </div>
        <div class="stats">
          <ul class="list-unstyled">
            <li><i class="fa fa-road fa-lg"></i><%= @data.distance %> Distance (Km)</li>
            <li><i class="fa fa-clock-o"></i><%= @data.duration %> Duration</li>
            <li><i class="fa fa-fire" ></i><%= @data.calories %> Calories</li>
          </ul>
        </div>
        <div class="map" data-waypoints=<%= @data.waypoints |> Poison.encode!  %>></div>
      </div>
      <%= link("list of runs", to: page_url(@conn, :index)) %>
    </div>
  </div>
</div>